### A - 500 Yen Coins

In [6]:
k,x = map(int, input().split())

print("Yes" if k * 500 >=  x else "No")

1 2
Yes


### B - Count ABC

In [33]:
n = int(input())
s = str(input())
cnt = 0
# s.count("ABC")  # これでは、nが使われてないのでダメらしい。
for i in range(n):
  if s[i:i+3].find("ABC") ==0:
    cnt = cnt+1
print(cnt)  

33
ABCCABCBABCCABACBCBBABCBCBCBCABCB
5


### C - Count Order

In [78]:
import numpy as np
import math

# print(math.factorial(5))

# input_N = int(input())#暫定OFF
p_list = np.array(list(map(int, input().split())))
# q_list = np.array(list(map(int, input().split())))#暫定OFF

# np.arange(1,input_N+1)

ord_sorted_list = np.where(np.sort(p_list) == p_list[0])
# print(type(ord_sorted_list[0]))
for i in range(len(p_list)):
    math.factorial(i)
# int(ord_sorted_list[0])


4 3 2 1


In [81]:
p_list = np.array(list(map(int, input().split())))

print(p_list)
input_N = 4

sorted_list = np.arange(1,input_N+1)
print(sorted_list)

# for i in range(1,len(p_list) +1):
#     print(np.where(p_list == i))

print(np.where(p_list == sorted_list[]))

4 3 2 1
[4 3 2 1]
[1 2 3 4]
(array([3]),)
(array([2]),)
(array([1]),)
(array([0]),)
